src/Entity/Equipes.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EquipesRepository")
 */
class Equipes
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $libelle;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $entraineur;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $creneaux;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_photo;

    /**
     * @ORM\Column(type="string", length=512, nullable=true)
     */
    private $url_result_calendrier;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $commentaire;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Matches", mappedBy="equipe_locale")
     */
    private $matches;

    public function __construct()
    {
        $this->matches = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getEntraineur(): ?string
    {
        return $this->entraineur;
    }

    public function setEntraineur(string $entraineur): self
    {
        $this->entraineur = $entraineur;

        return $this;
    }

    public function getCreneaux(): ?string
    {
        return $this->creneaux;
    }

    public function setCreneaux(string $creneaux): self
    {
        $this->creneaux = $creneaux;

        return $this;
    }

    public function getUrlPhoto(): ?string
    {
        return $this->url_photo;
    }

    public function setUrlPhoto(?string $url_photo): self
    {
        $this->url_photo = $url_photo;

        return $this;
    }

    public function getUrlResultCalendrier(): ?string
    {
        return $this->url_result_calendrier;
    }

    public function setUrlResultCalendrier(?string $url_result_calendrier): self
    {
        $this->url_result_calendrier = $url_result_calendrier;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(?string $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    /**
     * @return Collection|Matches[]
     */
    public function getMatches(): Collection
    {
        return $this->matches;
    }

    public function addMatch(Matches $match): self
    {
        if (!$this->matches->contains($match)) {
            $this->matches[] = $match;
            $match->setEquipeLocale($this);
        }

        return $this;
    }

    public function removeMatch(Matches $match): self
    {
        if ($this->matches->contains($match)) {
            $this->matches->removeElement($match);
            // set the owning side to null (unless already changed)
            if ($match->getEquipeLocale() === $this) {
                $match->setEquipeLocale(null);
            }
        }

        return $this;
    }
}

src/Entity/Matches.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MatchesRepository")
 */
class Matches
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Equipes", inversedBy="matches")
     * @JoinColumn(name="equipe_locale", referencedColumnName="id")
     */
    private $equipe_locale;

    /**
     * @ORM\Column(type="smallint")
     */
    private $domicile_exterieur;

    /**
     * @ORM\Column(type="string")
     */
    private $equipe_adverse;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_heure;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $num_semaine;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $num_journee;

    /**
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $gymnase;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEquipeLocale(): ?Equipes
    {
        return $this->equipe_locale;
    }

    public function setEquipeLocale(?Equipes $equipe_locale): self
    {
        $this->equipe_locale = $equipe_locale;

        return $this;
    }

    public function getDomicileExterieur(): ?int
    {
        return $this->domicile_exterieur;
    }

    public function setDomicileExterieur(int $domicile_exterieur): self
    {
        $this->domicile_exterieur = $domicile_exterieur;

        return $this;
    }

    public function getEquipeAdverse(): ?String
    {
        return $this->equipe_adverse;
    }

    public function setEquipeAdverse(String $equipe_adverse): self
    {
        $this->equipe_adverse = $equipe_adverse;

        return $this;
    }

    public function getDateHeure(): ?\DateTimeInterface
    {
        return $this->date_heure;
    }

    public function setDateHeure(?\DateTimeInterface $date_heure): self
    {
        $this->date_heure = $date_heure;

        return $this;
    }

    public function getNumSemaine(): ?int
    {
        return $this->num_semaine;
    }

    public function setNumSemaine(?int $num_semaine): self
    {
        $this->num_semaine = $num_semaine;

        return $this;
    }

    public function getNumJournee(): ?int
    {
        return $this->num_journee;
    }

    public function setNumJournee(?int $num_journee): self
    {
        $this->num_journee = $num_journee;

        return $this;
    }

    public function getGymnase(): ?string
    {
        return $this->gymnase;
    }

    public function setGymnase(?string $gymnase): self
    {
        $this->gymnase = $gymnase;

        return $this;
    }
}

src/Form/MatchesType.php
<?php

namespace App\Form;

use App\Entity\Matches;
use App\Entity\Equipes;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MatchesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('equipe_locale', EntityType::class, [
              'class' => Equipes::class,
              'choice_label' => 'libelle',
              'placeholder' =>  'Choisir une equipe'
            ])
            ->add('domicile_exterieur')
            ->add('equipe_adverse')
            ->add('date_heure', DateType::class, [
              'widget' => 'single_text'
            ])
            ->add('num_semaine')
            ->add('num_journee')
            ->add('gymnase')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Matches::class,
        ]);
    }
}

src/Controller/MatchesController.php
<?php

namespace App\Controller;

use App\Entity\Matches;
use App\Form\MatchesType;
use App\Repository\MatchesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/matches")
 */
class MatchesController extends AbstractController
{
    /**
     * @Route("/", name="matches_index", methods={"GET"})
     */
    public function index(MatchesRepository $matchesRepository): Response
    {
        return $this->render('matches/index.html.twig', [
            'matches' => $matchesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="matches_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $match = new Matches();
        $form = $this->createForm(MatchesType::class, $match);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($match);
            $entityManager->flush();

            return $this->redirectToRoute('matches_index');
        }

        return $this->render('matches/new.html.twig', [
            'match' => $match,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="matches_show", methods={"GET"})
     */
    public function show(Matches $match): Response
    {
        return $this->render('matches/show.html.twig', [
            'match' => $match,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="matches_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Matches $match): Response
    {
        $form = $this->createForm(MatchesType::class, $match);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('matches_index', [
                'id' => $match->getId(),
            ]);
        }

        return $this->render('matches/edit.html.twig', [
            'match' => $match,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="matches_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Matches $match): Response
    {
        if ($this->isCsrfTokenValid('delete'.$match->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($match);
            $entityManager->flush();
        }

        return $this->redirectToRoute('matches_index');
    }
}

templates/matches/_delete_form.html.twig
<form method="post" action="{{ path('matches_delete', {'id': match.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ match.id) }}">
    <button class="btn">Delete</button>
</form>

templates/matches/_equipes-show.html.twig
<div class="card">
  <img
    class="card-img-top"
    src="{{ asset('photos/' ~ equipe.urlPhoto) }}"
    alt="Logo {{ equipe.libelle }}"
  />
  <div class="card-body">
    <h5 class="card-title text-center">{{ equipe.libelle }}</h5>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Entraineur : {{ equipe.entraineur }}</li>
      <li class="list-group-item">Creneaux : {{ equipe.creneaux }}</li>
      <li class="list-group-item">Commentaire : {{ equipe.commentaire }}</li>
    </ul>
  </div>
</div>

templates/matches/_form.html.twig
{{ form_start(form) }}
  <div class="form-group">
    {{ form_label(form.equipe_locale)}}
    {{ form_widget(form.equipe_locale, {'attr': {'class': 'form-control'}}) }}
  </div>
  <div class="form-group">
    {{ form_label(form.domicile_exterieur)}}
    {{ form_widget(form.domicile_exterieur, {'attr': {'class': 'form-control'}}) }}
  </div>
  <div class="form-group">
    {{ form_label(form.equipe_adverse)}}
    {{ form_widget(form.equipe_adverse, {'attr': {'class': 'form-control'}}) }}
  </div>
  <div class="form-group">
    {{ form_label(form.date_heure)}}
    {{ form_widget(form.date_heure, {'attr': {'class': 'form-control'}}) }}
  </div>
  <div class="form-group">
    {{ form_label(form.num_semaine)}}
    {{ form_widget(form.num_semaine, {'attr': {'class': 'form-control'}}) }}
  </div>
  <div class="form-group">
    {{ form_label(form.num_journee)}}
    {{ form_widget(form.num_journee, {'attr': {'class': 'form-control'}}) }}
  </div>
  <div class="form-group">
    {{ form_label(form.gymnase)}}
    {{ form_widget(form.gymnase, {'attr': {'class': 'form-control'}}) }}
  </div>
    <button class="btn btn-outline-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/matches/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Matches{% endblock %}

{% block body %}
    <h1>Edit Matches</h1>

    {{ include('matches/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('matches_index') }}">back to list</a>

    {{ include('matches/_delete_form.html.twig') }}
{% endblock %}

templates/matches/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Matches index{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{{asset('css/dataTables.bootstrap4.min.css')}}" />
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/pages/matches-index.js') }}"></script>
{% endblock %}

{% block body %}
    <br />
    <a href="{{ path('matches_new') }}" class="btn btn-success">
      Ajouter un match <i class="fas fa-plus-square"></i>
    </a>
    <br />
    <table id="matches-table" class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>Equipe Locale</th>
                <th>Equipe Adverse</th>
                <th>Domicile Exterieur</th>
                <th>Date Heure</th>
                <th>Num Semaine</th>
                <th>Num Journee</th>
                <th>Gymnase</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for match in matches %}
            <tr>
                <td>{{ match.id }}</td>
                <td>{{ match.equipeLocale.libelle }}</td>
                <td>{{ match.equipeAdverse }}</td>
                <td>{{ match.domicileExterieur }}</td>
                <td>{{ match.dateHeure ? match.dateHeure|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ match.numSemaine }}</td>
                <td>{{ match.numJournee }}</td>
                <td>{{ match.gymnase }}</td>
                <td>
                    <a href="{{ path('matches_show', {'id': match.id}) }}">show</a>
                    <a href="{{ path('matches_edit', {'id': match.id}) }}">edit</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/matches/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Matches{% endblock %}

{% block body %}
    <h1>Create new Matches</h1>

    {{ include('matches/_form.html.twig') }}

    <a href="{{ path('matches_index') }}">back to list</a>
{% endblock %}

templates/matches/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Matches{% endblock %}

{% block body %}
    <br />
    <div class="card">
      <div class="card-body">
        <div class="row">
            {% set equipe = match.equipeLocale %}
            {% include ('equipes/_card.html.twig') %}
        </div>
        <br />
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Equipe adverse : {{ match.equipeAdverse }}</li>
          <li class="list-group-item">Location : {{ match.domicileExterieur ? 'Domicile' : 'Exterieur' }}</li>
          <li class="list-group-item">Date : {{ match.dateHeure ? match.dateHeure|date('Y-m-d H:i:s') : '' }}</li>
          <li class="list-group-item">Semaine : {{ match.numSemaine }}</li>
          <li class="list-group-item">Gymnase : {{ match.gymnase }}</li>
        </ul>
      </div>
    </div>
    
    <a href="{{ path('matches_index') }}">back to list</a>

    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('matches_edit', {'id': match.id}) }}">edit</a>
        {{ include('matches/_delete_form.html.twig') }}
    {% endif %}
{% endblock %}