src/Entity/Equipes.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EquipesRepository")
 */
class Equipes
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $libelle;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $entraineur;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $creneaux;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_photo;

    /**
     * @ORM\Column(type="string", length=512, nullable=true)
     */
    private $url_result_calendrier;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $commentaire;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Matches", mappedBy="equipe_locale")
     */
    private $matches;

    public function __construct()
    {
        $this->matches = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getEntraineur(): ?string
    {
        return $this->entraineur;
    }

    public function setEntraineur(string $entraineur): self
    {
        $this->entraineur = $entraineur;

        return $this;
    }

    public function getCreneaux(): ?string
    {
        return $this->creneaux;
    }

    public function setCreneaux(string $creneaux): self
    {
        $this->creneaux = $creneaux;

        return $this;
    }

    public function getUrlPhoto(): ?string
    {
        return $this->url_photo;
    }

    public function setUrlPhoto(?string $url_photo): self
    {
        $this->url_photo = $url_photo;

        return $this;
    }

    public function getUrlResultCalendrier(): ?string
    {
        return $this->url_result_calendrier;
    }

    public function setUrlResultCalendrier(?string $url_result_calendrier): self
    {
        $this->url_result_calendrier = $url_result_calendrier;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(?string $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    /**
     * @return Collection|Matches[]
     */
    public function getMatches(): Collection
    {
        return $this->matches;
    }

    public function addMatch(Matches $match): self
    {
        if (!$this->matches->contains($match)) {
            $this->matches[] = $match;
            $match->setEquipeLocale($this);
        }

        return $this;
    }

    public function removeMatch(Matches $match): self
    {
        if ($this->matches->contains($match)) {
            $this->matches->removeElement($match);
            // set the owning side to null (unless already changed)
            if ($match->getEquipeLocale() === $this) {
                $match->setEquipeLocale(null);
            }
        }

        return $this;
    }
}

src/Entity/Matches.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MatchesRepository")
 */
class Matches
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Equipes", inversedBy="matches")
     * @JoinColumn(name="equipe_locale", referencedColumnName="id")
     */
    private $equipe_locale;

    /**
     * @ORM\Column(type="smallint")
     */
    private $domicile_exterieur;

    /**
     * @ORM\Column(type="string")
     */
    private $equipe_adverse;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_heure;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $num_semaine;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $num_journee;

    /**
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $gymnase;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEquipeLocale(): ?Equipes
    {
        return $this->equipe_locale;
    }

    public function setEquipeLocale(?Equipes $equipe_locale): self
    {
        $this->equipe_locale = $equipe_locale;

        return $this;
    }

    public function getDomicileExterieur(): ?int
    {
        return $this->domicile_exterieur;
    }

    public function setDomicileExterieur(int $domicile_exterieur): self
    {
        $this->domicile_exterieur = $domicile_exterieur;

        return $this;
    }

    public function getEquipeAdverse(): ?String
    {
        return $this->equipe_adverse;
    }

    public function setEquipeAdverse(String $equipe_adverse): self
    {
        $this->equipe_adverse = $equipe_adverse;

        return $this;
    }

    public function getDateHeure(): ?\DateTimeInterface
    {
        return $this->date_heure;
    }

    public function setDateHeure(?\DateTimeInterface $date_heure): self
    {
        $this->date_heure = $date_heure;

        return $this;
    }

    public function getNumSemaine(): ?int
    {
        return $this->num_semaine;
    }

    public function setNumSemaine(?int $num_semaine): self
    {
        $this->num_semaine = $num_semaine;

        return $this;
    }

    public function getNumJournee(): ?int
    {
        return $this->num_journee;
    }

    public function setNumJournee(?int $num_journee): self
    {
        $this->num_journee = $num_journee;

        return $this;
    }

    public function getGymnase(): ?string
    {
        return $this->gymnase;
    }

    public function setGymnase(?string $gymnase): self
    {
        $this->gymnase = $gymnase;

        return $this;
    }
}

src/Form/EquipesType.php
<?php

namespace App\Form;

use App\Entity\Equipes;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EquipesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('libelle')
            ->add('entraineur')
            ->add('creneaux')
            ->add('url_photo')
            ->add('url_result_calendrier')
            ->add('commentaire')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Equipes::class,
        ]);
    }
}

src/Controller/EquipesController.php
<?php

namespace App\Controller;

use App\Entity\Equipes;
use App\Form\EquipesType;
use App\Repository\EquipesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/equipes")
 */
class EquipesController extends AbstractController
{
    /**
     * @Route("/", name="equipes_index", methods={"GET"})
     * @param EquipesRepository $equipesRepository
     * @return Response
     */
    public function index(EquipesRepository $equipesRepository): Response
    {
        return $this->render('equipes/index.html.twig', [
            'equipes' => $equipesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="equipes_new", methods={"GET","POST"})
     *
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $equipe = new Equipes();
        $form = $this->createForm(EquipesType::class, $equipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($equipe);
            $entityManager->flush();

            return $this->redirectToRoute('equipes_index');
        }

        return $this->render('equipes/new.html.twig', [
            'equipe' => $equipe,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="equipes_show", methods={"GET"})
     *
     * @param Equipes $equipe
     * @return Response
     */
    public function show(Equipes $equipe): Response
    {
        return $this->render('equipes/show.html.twig', [
            'equipe' => $equipe,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="equipes_edit", methods={"GET","POST"})
     *
     * @param Request $request
     * @param Equipes $equipe
     * @return Response
     */
    public function edit(Request $request, Equipes $equipe): Response
    {
        $form = $this->createForm(EquipesType::class, $equipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('equipes_index', [
                'id' => $equipe->getId(),
            ]);
        }

        return $this->render('equipes/edit.html.twig', [
            'equipe' => $equipe,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="equipes_delete", methods={"DELETE"})
     *
     * @param Request $request
     * @param Equipes $equipe
     * @return Response
     */
    public function delete(Request $request, Equipes $equipe): Response
    {
        if ($this->isCsrfTokenValid('delete'.$equipe->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($equipe);
            $entityManager->flush();
        }

        return $this->redirectToRoute('equipes_index');
    }
}

templates/equipes/_card.html.twig
<div class="col-sm-6">
    <div class="card">
        <img class="card-img-top" src="{{ asset('photos/' ~ equipe.urlPhoto) }}" alt="Photo d'équipe">
        <div class="card-body">
            <h5 class="card-title">{{ equipe.libelle }}</h5>
            <p class="card-text">{{ equipe.commentaire|default('Pas de commentaire') }}</p>
        </div>
    </div>
</div>
<div class="col-sm-6">
    <div class="card" >
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><strong>ID : </strong>{{ equipe.id}}</li>
            <li class="list-group-item"><strong>Entraineur : </strong>{{ equipe.entraineur }}</li>
            <li class="list-group-item"><strong>Créneaux : </strong>{{ equipe.creneaux }}</li>
            <li class="list-group-item"><a href="{{ equipe.urlResultCalendrier }}">Résultats</a></li>
        </ul>
    </div>
</div>

templates/equipes/_delete_form.html.twig
<form method="post" action="{{ path('equipes_delete', {'id': equipe.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette équipe?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ equipe.id) }}">
    <button class="btn btn-outline-danger" data-toggle="tooltip" data-placement="right" title="Supprimer">
        <i style="width: 18px;height: 16px;" class="fas fa-trash"></i>
    </button>
</form>

templates/equipes/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn btn-outline-success" data-toggle="tooltip" data-placement="right" title="{{ button_label|default('Enregistrer') }}">
            <i class="fas fa-save "></i>
        </button>
{{ form_end(form) }}

templates/equipes/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Equipes{% endblock %}

{% block body %}
    <h1>Edit Equipes</h1>

    {{ include('equipes/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
    {{ include('equipes/_delete_form.html.twig') }}
    <a class="btn btn-outline-primary" href="{{ path('equipes_index') }}" data-toggle="tooltip" data-placement="right" title="Retour aux équipes">
        <i class="fas fa-backward"></i>
    </a>

{% endblock %}

templates/equipes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les équipes{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{{asset('css/dataTables.bootstrap4.min.css')}}" />
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/pages/team-index.js') }}"></script>
{% endblock %}

{% block body %}
    <div>
        <br>
        <a href="{{ path('equipes_new') }}" class="btn btn-success">
            Ajouter une équipe <i class="fas fa-plus-square"></i>
        </a>
        <br>
        <br>
        <table id="team-table" class="table table-striped table-bordered" >
            <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th>Entraineur</th>
                <th>Commentaire</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for equipe in equipes %}
                <tr>
                    <td>{{ equipe.id }}</td>
                    <td>{{ equipe.libelle }}</td>
                    <td>{{ equipe.entraineur }}</td>
                    <td>{{ equipe.commentaire }}</td>
                    <td>
                        <a href="{{ path('equipes_show', {'id': equipe.id}) }}" class="btn btn-outline-primary" data-toggle="tooltip" data-placement="right" title="Voir">
                            <i class="fas fa-eye"></i>
                        </a>
                        {% if is_granted('ROLE_ADMIN') %}
                            <a href="{{ path('equipes_edit', {'id': equipe.id}) }}" class="btn btn-outline-info" data-toggle="tooltip" data-placement="right" title="Modifier">
                                <i class="fas fa-edit"></i>
                            </a>
                            {{ include('equipes/_delete_form.html.twig') }}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/equipes/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Equipes{% endblock %}

{% block body %}
    <h1>Create new Equipes</h1>

    {{ include('equipes/_form.html.twig') }}
    <a class="btn btn-outline-primary" href="{{ path('equipes_index') }}" data-toggle="tooltip" data-placement="right" title="Retour aux équipes">
        <i class="fas fa-backward"></i>
    </a>

{% endblock %}

templates/equipes/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Equipes{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{{asset('css/dataTables.bootstrap4.min.css')}}" />
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/pages/matches-index.js') }}"></script>
{% endblock %}

{% block body %}
    <h1>Equipes</h1>

    <div class="row">
        {% include ('equipes/_card.html.twig') %}
    </div>
    <br>
    <div class="button-group">
        <a href="{{ path('equipes_index') }}" class="btn btn-outline-primary" data-toggle="tooltip" data-placement="top" title="Retour">
            <i class="fas fa-backward"></i>
        </a>
        {% if is_granted('ROLE_ADMIN') %}
            <a href="{{ path('equipes_edit', {'id': equipe.id}) }}"  class="btn btn-outline-success" data-toggle="tooltip" data-placement="top" title="Modifier">
                <i class="fas fa-edit"></i>
            </a>
            {{ include('equipes/_delete_form.html.twig') }}
        {% endif %}
    </div>
    <br>
    <table id="matches-table" class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>Equipe Adverse</th>
                <th>Domicile Exterieur</th>
                <th>Date Heure</th>
                <th>Num Semaine</th>
                <th>Num Journee</th>
                <th>Gymnase</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for match in equipe.matches %}
            <tr>
                <td>{{ match.id }}</td>
                <td>{{ match.equipeAdverse }}</td>
                <td>{{ match.domicileExterieur }}</td>
                <td>{{ match.dateHeure ? match.dateHeure|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ match.numSemaine }}</td>
                <td>{{ match.numJournee }}</td>
                <td>{{ match.gymnase }}</td>
                <td>
                    <a href="{{ path('matches_show', {'id': match.id}) }}" class="btn btn-outline-primary" data-toggle="tooltip" data-placement="right" title="Voir">
                        <i class="fas fa-eye"></i>
                    </a>
                    <a href="{{ path('matches_edit', {'id': match.id}) }}" class="btn btn-outline-info" data-toggle="tooltip" data-placement="right" title="Modifier">
                        <i class="fas fa-edit"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}